export const data = [
  {
    routeId: 1,
    from: 'New Delhi',
    to: 'Mumbai',
    availableSeats: [
      { seat: 1, available: true },
      { seat: 2, available: true },
      { seat: 3, available: false },
      { seat: 4, available: false },
      { seat: 5, available: true },
      { seat: 6, available: true },
      { seat: 7, available: false },
      { seat: 8, available: false },
      { seat: 9, available: true },
      { seat: 10, available: false },
    ],
  },
  {
    routeId: 2,
    from: 'New Delhi',
    to: 'Bangalore',
    availableSeats: [
      { seat: 1, available: true },
      { seat: 2, available: false },
      { seat: 3, available: false },
      { seat: 4, available: false },
      { seat: 5, available: true },
      { seat: 6, available: false },
      { seat: 7, available: true },
      { seat: 8, available: false },
      { seat: 9, available: true },
      { seat: 10, available: true },
    ],
  },
  {
    routeId: 3,
    from: 'Jaipur',
    to: 'Bangalore',
    availableSeats: [
      { seat: 1, available: true },
      { seat: 2, available: true },
      { seat: 3, available: true },
      { seat: 4, available: false },
      { seat: 5, available: true },
      { seat: 6, available: true },
      { seat: 7, available: true },
      { seat: 8, available: false },
      { seat: 9, available: true },
      { seat: 10, available: false },
    ],
  },
  {
    routeId: 4,
    from: 'Jaipur',
    to: 'Mumbai',
    availableSeats: [
      { seat: 1, available: true },
      { seat: 2, available: true },
      { seat: 3, available: false },
      { seat: 4, available: true },
      { seat: 5, available: true },
      { seat: 6, available: false },
      { seat: 7, available: true },
      { seat: 8, available: true },
      { seat: 9, available: false },
      { seat: 10, available: true },
    ],
  },
]
